//We have one more App constant file for SVG generation
//Untill we fix or figure out how to make single file
//please maintain same changes or fields in both the files.

import { ORIENTATION_BREAKPOINTS } from "@angular/flex-layout";

//File name: svg-constants.ts
export const AppConstantSpace =
{
  MAX_FACINGX_MSG: ' You are exceeding Max Facings for Product ',
  MIN_FACINGX_MSG: ` You can't be lower then Min Facings for Product `,
  MAX_FACINGY_MSG: ' You are exceeding Max FacingsY for Product ',
  MIN_FACINGY_MSG: ` You can't be lower then Min FacingsY for Product `,
  MAX_LAYOVERS_MSG: ' You are exceeding Max LayoversY for Product ',
  MIN_LAYOVERS_MSG: ` You can't be lower then Min LayoversY for Product `,
  FACINGX: 'FacingsX',
  FACINGY: 'FacingsY',
  LAYOVERSY: 'LayoversY',
  ARD: 'ADRI',
  NUMERIC_RANGE: 'Numeric Range',
  STRING_MATCH: 'String Match',
  ASST_ACTION: 'Asst Action',
  CONVERT_TO_PIXEL_VALUE: 9.6,
  SPACE_NOT_AVAILABLE: ' No space available',
  CAN_NOT_ROTATE: ' Cannot Rotate ',
  SPACE_NOT_AVAILABLE_ROTATE: 'space not available with parent also for rotation',
  POSITIONOBJECT: 'Position' as 'Position',
  BLOCKOBJECT: 'Block',
  NESTEDBLOCKOBJECT: 'NestedBlock',
  BLOCKORDERPARENT: 'Parent',
  BLOCKORDERNESTED: 'Nested',
  FIXTUREOBJ: 'Fixture' as 'Fixture',
  GRILLOBJ: 'Grill' as 'Grill',
  STANDARDSHELFOBJ: 'StandardShelf' as 'StandardShelf',
  PEGBOARDOBJ: 'Pegboard' as 'Pegboard',
  SHOPPINGCARTOBJ: 'ShoppingCart' as 'ShoppingCart',
  BLOCK_FIXTURE: 'BlockFixture' as 'BlockFixture',
  COFFINCASEOBJ: 'CoffinCase' as 'CoffinCase',
  SLOTWALLOBJ: 'Slotwall' as 'Slotwall',
  CROSSBAROBJ: 'Crossbar' as 'Crossbar',
  BASKETOBJ: 'Basket' as 'Basket',
  SECTIONOBJ: 'Section' as 'Section',
  MODULAR: 'Modular' as 'Modular',
  BAY: 'Bay',
  POG: 'POG',
  ANNOTATION: 'Annotation',
  DIVIDERS: 'Divider' as 'Divider',
  BAGSHELF: 'BagShelf',
  MOVEMENT: 'LKFixtureMovement',
  UPRIGHT: 'Upright',
  UPRIGHT_DESC_DATA: '_UprightType.DescData',
  SET_UPRIGHT_TO_BAY_WIDTH: '_SetUprightToBayWidth.FlagData',
  SECTION: 'section',
  POSITION_LIKE: 'positionLike',
  OBJECT: 'object',
  FITCHECK_OK: 0,
  FITCHECK_COLLISION: 1,
  FITCHECK_TOO_TALL: 2,
  FITCHECK_OUTSIDE: 3,
  FITCHECK_TOO_TALL_OK: 4,
  FITCHECK_COLLISION_OK: 5,
  FITCHECK_OUTSIDE_OK: 6,
  FITCHECK_TOO_DEEP: 7,
  FITCHECK_TOO_DEEP_OK: 8,
  ON: 'ON',
  OFF: 'OFF',
  Collision: 'Collision',
  LOCATION_X: 'Location.X',
  LOCATION_Y: 'Location.Y',
  FIXTURE_WIDTH: 'Fixture.Width',
  STANDARDSHELF: 'standardshelf',
  PEGBOARD: 'pegboard',
  SLOTWALL: 'slotwall',
  CROSSBAR: 'crossbar',
  POS_LKDIVIDERTYPE: 'Position.LKDividerType',
  FIXTUREGALLERYPOGTYPE: -1,
  bayHighLighterZIndex: 10,
  spanShelfZIndex: 8,
  DIVIDEROBJECTMODEL: 7,
  FIXTUREOBJECTMODEL: 0,
  GRILLSOBJECTMODEL: 6,
  STANDARDSHELFOBJECTMODEL: 1,
  CROSSBAROBJECTMODEL: 2,
  PEGBOARDOBJECTMODEL: 3,
  BLOCKFIXTUREOBJECTMODEL: 5,
  POGSTATUS: {
    'EXPERIMENTAL': 1,
    'DRAFT': 2,
    'ACTIONABLE': 3,
    'PENDING': 4,
    'LIVE': 5,
    'RETIRED': 6
  },
  COFFINCASE: 'coffincase',
  BASKET: 'basket',
  SYSTEM: 'system',
  MERCH_DEFAULT: 100,
  MERCH_MULTI_ORIENT: 200,
  MERCH_PYRAMID_BASE: 300,
  MERCH_HALF_PYRAMID: 301,
  MERCH_PYRAMID: 302,
  MERCH_RECTANGLE_LOG: 303,
  MERCH_ABOVE: 305,
  MERCH_ABOVE_TEXT: '305',
  MERCH_BEHIND: 306,
  MERCH_BEHIND_TEXT: '306',
  MERCH_MANUAL: 307,
  MERCH_MANUAL_TEXT: '307',
  MERCH_BASKET: 400,
  MERCH_LOOSE: 500,
  MERCH_ADVANCED_TRAY: 101,
  FITCHECKTOLERANCE: 1,
  KEYDOWNEVENTJSON: {
    '<': 'FACINGSCHANGE',
    '>': 'FACINGSCHANGE',
    '49': 'FACINGSCHANGE',
    '50': 'FACINGSCHANGE',
    '51': 'FACINGSCHANGE',
    '52': 'FACINGSCHANGE',
    '53': 'FACINGSCHANGE',
    '54': 'FACINGSCHANGE',
    '55': 'FACINGSCHANGE',
    '56': 'FACINGSCHANGE ',
    '57': 'FACINGSCHANGE',
    '97': 'FACINGSCHANGE',
    '98': 'FACINGSCHANGE',
    '99': 'FACINGSCHANGE',
    '100': 'FACINGSCHANGE',
    '101': 'FACINGSCHANGE',
    '102': 'FACINGSCHANGE',
    '103': 'FACINGSCHANGE',
    '104': 'FACINGSCHANGE',
    '105': 'FACINGSCHANGE',
    '46': 'DELETE'
  },
  SHIFTKEYDOWNEVENTJSON: {
    '<': 'FACINGSCHANGE',
    '>': 'FACINGSCHANGE',
    '38': 'ROLLUPDOWN',
    '40': 'ROLLUPDOWN'
  },
  CTRLKEYDOWNEVENTJSON: {
    'v': 'PASTE',
    'c': 'COPY',
    'x': 'CUT',
    'i': 'FLIP',
    'ArrowLeft': 'MOVEPOS',
    'ArrowRight': 'MOVEPOS',
    'ArrowDown': 'MOVEFIX',
    'ArrowUp': 'MOVEFIX'
  },
  PROPERTYGRID_ALLOWED_DICTIONARIES: {
    'POSITION_PROPERTIES': [394],
    'FIXTURE_PROPERTIES': [],
    'SECTION_PROPERTIES': [219, 582, 459]
  },
  DATE_TIME_FORMAT: 'dd MMM yyyy hh:mm:ss tt',
  DATE_FORMAT: 'dd MMM yyyy',
  ABSKEYGROUP: 'ABS',
  ACTIONS: {
    'FACINGS': 1,
    'DELETE': 2,
    'DRAGDROP': 3,
    'ORIENTATION': 4,
    'COPYPASTE': 5,
    'ALLOCATION': 6
  },
  CHILD_INTERSECTION_IDENTIFIER: 'Children-intersection',
  GERMAN_LANGUAGE_IDENTIFIER: 'de-DE',
  DEFAULT_PREVIEW_SMALL_IMAGE: '/Areas/ShelfPlanning/ClientApp/assets/images/default-preview-small.png',
  DEFAULT_PREVIEW_IMAGE: '/Areas/ShelfPlanning/ClientApp/assets/images/default-preview.gif',
  NO_IMAGE: '/Areas/iShelf/ClientApplication/appMaterial/css/themes/default/img/no-img.png',
  CLEAR_FOOTER_MSG_TIMER: 2500,
  PLANOGRAM_LIBRARY_PIN_STATUS: 'planogramLibraryPinStatus',
  SELECTALL:'selectAll',
  WHITESPACE:'whiteSpace',
  UP:'UP',
  DOWN:'DOWN',
  MULTIFIXEDIT: 'MULTIFIXEDIT',
  ADVANCEDTRAYCAPPING: {
    CAP_TRAY_FRONTS: 'advanced-unit-capping-fronts',
    CAP_TRAY_DEPTHS:'advanced-unit-capping-depths',
    CAP_TRAY_BOTH: 'advanced-unit-capping-both',
  },
  FRONTCAPPING: 1,
  DEPTHCAPPING: 2,
  FRONT_DEPTHCAPPING: 3,
  REMOVE_ADVANCED_CAPPING: 'remove-advanced-capping',
  FILLSTATUS: {
    FILLED: 0,
    NO_SPACE: 1,
    MAX_CONSTRAINT: 2
  },
  PKGSTYLE_UNIT:0,
  PKGSTYLE_TRAY:1,
  DIVIDER_FACINGS_LEFT:2,
  INHERIT_FROM_SHELF:-1,
  FIXTURE_MOVEMENT: {
    FREE_FORM: 0,
    MOVE_BY_NOTCH: 1,
    LOCK: 2
  },
  FIRST_NOTCH: 'FirstNotch',
  FIXTURE_NOTCH_NUMBER: 'Fixture.NotchNumber',
  NOTCH_SPACE: 'Notch',
  POG_IMPLEMENTATION_DATE_ENABLE: 'POG_IMPLEMENTATION_DATE_ENABLE',
  PLATFORM: 'PLATFORM',
  FIXTURE_IGNORE_MERCH_HEIGHT:'Fixture.IgnoreMerchHeight',
  FIXTURE_IGNORE_FINGER_SPACE:'Fixture.IgnoreFingerSpace',
  ORIENTATION: {
    FRONTBOTTOM: 0,
    FRONTRIGHT: 1,
    FRONTTOP: 2,
    FRONTLEFT: 3,
    LEFTBOTTOM: 4,
    LEFTFRONT: 5,
    LEFTTOP: 6,
    LEFTBACK: 7,
    TOPFRONT: 8,
    TOPRIGHT: 9,
    TOPBACK: 10,
    TOPLEFT: 11,
    BACKBOTTOM: 12,
    BACKLEFT: 13,
    BACKTOP: 14,
    BACKRIGHT: 15,
    RIGHTBOTTOM: 16,
    RIGHTBACK: 17,
    RIGHTTOP: 18,
    RIGHTFRONT: 19,
    BOTTOMBACK: 20,
    BOTTOMRIGHT: 21,
    BOTTOMFRONT: 22,
    BOTTOMLEFT: 23
  },
  ORIENTATION_VIEW: {
    FRONT: 0,
    LEFT: 1,
    TOP: 2,
    BACK: 3,
    RIGHT: 4,
    BOTTOM: 5
  },
  COFFIN_POSITION_ALIGNMENT:{
    LEFT: "left",
    RIGHT: "right",
    TOP: "top",
    BOTTOM: "bottom",
  },
  TRAFFICFLOW: {
    LEFT_TO_RIGHT: 1,
    RIGHT_TO_LEFT: 2
  },
  STANDARDSHELFPOSTION: {
    POSITION_MOVEMENT: 'USER_DEFAULTS.STANDARDSHELF.POSITION_MOVEMENT'
  },
  COFFINPOSTION: {
    POSITION_MOVEMENT: 'USER_DEFAULTS.COFFIN.POSITION_MOVEMENT'
  },
  POSITION_MOVEMENT_TYPE: {
    DIRECT: 'Direct',
    STEP_BY_STEP: 'StepByStep'
  },
  POSITION_DIRECTION: {
    LEFT: "Left",
    RIGHT: "Right",
    UP: "Up",
    DOWN: "Down"
  },
  VERTICALFLOW: {
    TOP_TO_BOTTOM: 1,
    BOTTOM_TO_TOP: 0
  },
  GRAPH_TYPE: {
    PIE_CHART: 1,
    BAR_GRAPH: 2,
    GRID_DATA: 3
  }
}
