export const PosIntersectionArray = [
    'Position.MinFacingsX',
    'Position.MinFacingsY',
    'Position.FacingsX',
    'Position.FacingsY',
    'Position.LayoversY',
    'Location.X',
    'Location.Y',
    'Position.IDOrientation',
    'Position.GapX',
    'Position.GapY',
    'Position.SKUGapX',
    'Position.SKUGapY',
    'Position.ProductPackage.XPegHole',
    'Position.ProductPackage.YPegHole',
    'Position.ProductPackage.Height',
    'Position.ProductPackage.Width',
    'Position.ProductPackage.Depth',
    'Position.ProductPackage.NestingX',
    'Position.MaxFacingsX',
    'Position.MaxFacingsY',
    'Position.LKDividerType',
];

export const FixtureIntersectionArray = [
    'Fixture.MaxMerchHeight',
    'Location.X',
    'Location.Y',
    'Location.Z',
    'Fixture.DividerHeight',
    'Fixture.DividerWidth',
    'Rotation.X',
    'Fixture.Thickness',
    'Fixture.Width',
    'Fixture.Height',
    'Fixture.SnapToLeft',
    'Fixture.SnapToRight',
    'Fixture._X04_XINC.ValData',
    'Fixture._X04_YINC.ValData',
    'Fixture._X04_XPEGSTART.ValData',
    'Fixture._X04_XPEGEND.ValData',
    'Fixture._X04_YPEGEND.ValData',
    'Fixture._X04_YPEGSTART.ValData',
    'Fixture.LKCrunchMode',
    'Fixture.CanJoin',
    'Fixture.OverhangXLeft',
    'Fixture.OverhangXRight',
];

export const PogIntersectionArray = [
    'fitCheck',
    '_IsSpanAcrossShelf.FlagData',
    'IsVariableHeightShelf',
    'SuppressFingerSpace',
    'Dimension.Width',
    'Dimension.Height',
    'Dimension.Depth',
];
