export const KendoGridConfigMockData = {
  inputGridConfigMock: {
    gridConfig: {
      columnConfig: true,
      columnMenuDisplay: true,
      columns: [
        {
          columnMenu: true,
          description: 'Width',
          editable: false,
          field: 'width_template',
          filterable: { multi: true, search: true },
          format: null,
          groupOrder: 0,
          groupable: false,
          hidden: false,
          locked: false,
          orderIndex: 0,
          sortable: { initialDirection: null },
          sortorder: 0,
          style: '',
          templateDummy: 'dataItem.width*0.083333',
          title: 'Width',
          type: 'float',
          width: 30
        },
        {
          columnMenu: true,
          description: 'Depth of planogram measured in inches',
          editable: false,
          field: 'depth',
          filterable: { multi: true, search: true },
          format: null,
          groupOrder: 0,
          groupable: false,
          hidden: false,
          locked: false,
          orderIndex: 1,
          sortable: { initialDirection: 'desc' },
          sortorder: 0,
          style: '',
          templateDummy: '',
          title: 'Depth',
          type: 'number',
          width: 30
        },
        {
          columnMenu: true,
          description: 'Proposed Planogram Number',
          editable: false,
          field: 'generatedPogId_template',
          filterable: { multi: true, search: true },
          format: null,
          groupOrder: 0,
          groupable: false,
          hidden: false,
          locked: false,
          orderIndex: 2,
          sortable: { initialDirection: null },
          sortorder: 0,
          style: '',
          templateDummy: '`<button`> `+ dataItem.generatedPogId +`</button>`',
          title: 'P Pog#',
          type: 'string',
          width: 10
        },
        {
          columnMenu: true,
          description: 'Fixture Configuration',
          editable: false,
          field: 'fixtureConfig',
          filterable: { multi: true, search: true },
          format: null,
          groupOrder: 0,
          groupable: false,
          hidden: false,
          locked: false,
          orderIndex: 3,
          sortable: { initialDirection: null },
          sortorder: 0,
          style: '',
          templateDummy: '',
          title: 'Fixture Configuration',
          type: 'string',
          width: 30
        },
        {
          columnMenu: true,
          description: 'Stores',
          editable: false,
          field: 'stores_template',
          filterable: { multi: true, search: true },
          format: null,
          groupOrder: 0,
          groupable: false,
          hidden: false,
          locked: false,
          orderIndex: 4,
          sortable: { initialDirection: null },
          sortorder: 0,
          style: '',
          templateDummy: '`<button `> `+ dataItem.stores +`</button>`',
          title: 'Stores',
          type: 'string',
          width: 30
        },
        {
          columnMenu: true,
          description: 'Reset',
          editable: false,
          field: 'reset_template',
          filterable: { multi: true, search: true },
          format: null,
          groupOrder: 0,
          groupable: false,
          hidden: false,
          locked: false,
          orderIndex: 5,
          sortable: { initialDirection: null },
          sortorder: 0,
          style: '',
          templateDummy: '`<button `> Reset </button>`',
          title: 'Reset',
          type: 'string',
          width: 30
        }
      ],
      data: [
        {
          Only_fixtureConfig: '36x36',
          StoreWidthinFeet: 6,
          bayInfo: [],
          depth: 20,
          fixtureConfig: '<span>3<sup>7</sup></span>x<span>3<sup>7</sup></span>',
          generatedPogId: 1690697,
          isApproved: false,
          isVerified: false,
          pogName: '06\' SALAD DRESSING PREMIUM',
          pogs: [],
          storeModel: null,
          storeModelVerified: false,
          storeTempModel: null,
          stores: 1,
          width: 72
        }
      ],
      fillDownRequired: true,
      firstCheckBoxColumn: true,
      height: 'calc(100vh - 180px)',
      id: 'bayMappingStoreGrid',
      isRowSelectableByCheckbox: true
    },
    groups: [],
    sort: [
      { field: 'depth', dir: 'desc' }
    ]
  },

  lockUnlockMock: {
    color: '#F5F5F5',
    columnDescription: 'Width',
    columnTitle: 'Width',
    columnfield: 'width_template',
    fontColor: '#656565',
    isHide: false,
    isLocked: false,
    searchcss: false,
    sortDir: ''
  }
};
