export const PogCompareMockData = {
  PogCompareGridData: [
    {
      blockColor: '#CF71AF   ',
      blockName: 'F4_Block1',
      brand: 'PAMPERS         ',
      casePack: 4,
      casepack: 4,
      color: null,
      corpId: 4,
      csc: '118181',
      defaultMerchStyle: 0,
      defaultOrientation: 0,
      descSize: '32 CT',
      eTag: null,
      fixtureNumber: 4,
      idProduct: 1779208,
      idpogObject: '118181',
      imageData: '',
      internalStatus: 10,
      isLocalItem: false,
      isMustStock: false,
      isNpi: false,
      isPreserveList: false,
      l1: 'BABY DIAPER',
      l2: 'BABY FOOD/DIAPERS/BABY CARE',
      l3: 'DISPOSABLE DIAPERS',
      l4: 'JUMBO/2X DISPOSABLE DIAPERS',
      l5: 'PAMPERS BSOD JUMBO/2X DISPOSABLE DIAPERS',
      l6: 'SIZE 1 - SMALL PAMPERS BSOD JUMBO/2X',
      l7: null,
      l8: null,
      l9: null,
      l10: null,
      manufacturer: 'PROCTER & GAMBLE',
      name: 'PAMPERS SWAD S1 JUMBO',
      packData: '}}',
      packageImage: { UNIT: {} },
      packageInfo: { UNIT: {} },
      partitionKey: '4',
      plCapacity: 8,
      plCases: '2.00',
      plDos: 130.91,
      plFacing: 2,
      plFacingsX: 0,
      plFacingsY: 1,
      plFacingsZ: 4,
      plLayoverY: 0,
      plLayoverZ: 2,
      plLocationX: 6.22,
      plLocationY: 0,
      plLocationZ: 0,
      plPackName: 'UNIT',
      plidOrientation: 1,
      positionNumber: 2,
      prCapacity: 4,
      prCases: '1.00',
      prDos: 40,
      prFacing: 1,
      prFacingsX: 0,
      prFacingsY: 1,
      prFacingsZ: 4,
      prLayoverY: 0,
      prLayoverZ: 0,
      prLocationX: 11.327272727272728,
      prLocationY: 0,
      prLocationZ: 0,
      prPackName: 'UNIT',
      pridOrientation: 1,
      refSKU: '65150689',
      refUPC: '3700074956',
      rowKey: '118181',
      sku: '65150689',
      storeSKU: null,
      storeUPC: null,
      timestamp: '0001-01-01T00:00:00+00:00',
      unitMovement: 0.061111111111111116,
      upc: '3700074956',
      wic: false
    }
  ],
  PogCompareGridColumn: [
    {
      0: 'UPC',
      1: 'upc',
      2: 0,
      field: 'pl',
      3: true,
      4: true,
      5: false,
      6: false,
      7: 0,
      8: 300,
      9: false,
      10: 'string',
      11: 'UPC of the product',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 2626,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'CSC',
      1: 'csc',
      2: 1,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 130,
      9: false,
      10: 'string',
      11: 'Selling code of the product',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 2627,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'CIC ',
      1: 'sku',
      2: 2,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 100,
      9: false,
      10: 'number',
      11: 'CIC of the item',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 2628,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Case Pack',
      1: 'casepack',
      2: 3,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 200,
      9: false,
      10: 'number',
      11: 'Number of units of the items',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 2629,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Desc Size',
      1: 'descSize',
      2: 4,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 150,
      9: false,
      10: 'number',
      11: 'Descriptive size and unit of measure',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 2630,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Facings',
      1: 'plFacing',
      2: 5,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 150,
      9: false,
      10: 'number',
      11: 'Facing of the item',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 2631,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Cases',
      1: 'plCases',
      2: 6,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 100,
      9: false,
      10: 'number',
      11: 'Number of cases used. Calculated as item capacity by case pack',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 2632,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Dos',
      1: 'plDos',
      2: 7,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 115,
      9: false,
      10: 'number',
      11: 'Days of supply of the item',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 2633,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Capacity',
      1: 'plCapacity',
      2: 8,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 100,
      9: false,
      10: 'number',
      11: 'Number of units of the items',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 2634,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Facings',
      1: 'prFacing',
      2: 9,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 120,
      9: false,
      10: 'number',
      11: 'Facing of the item',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 2635,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Cases',
      1: 'prCases',
      2: 10,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 100,
      9: false,
      10: 'number',
      11: 'Number of cases used. Calculated as item capacity by case pack',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 2636,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Dos',
      1: 'prDos',
      2: 11,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 115,
      9: false,
      10: 'number',
      11: 'Days of supply of the item',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 2637,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Capacity',
      1: 'prCapacity',
      2: 12,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 100,
      9: false,
      10: 'number',
      11: 'Number of units of the items',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 2638,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Block Name',
      1: 'blockName',
      2: 13,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 150,
      9: false,
      10: 'string',
      11: 'Name of the block in model',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 3216,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Block Color',
      1: 'blockColor',
      2: 14,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 150,
      9: false,
      10: 'string',
      11: 'Block Color',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 3217,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Fixture #',
      1: 'fixtureNumber',
      2: 15,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 150,
      9: false,
      10: 'number',
      11: 'Fixture #',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 3218,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Position #',
      1: 'positionNumber',
      2: 16,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 150,
      9: false,
      10: 'number',
      11: 'Position #',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 3219,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Is Local Item',
      1: 'isLocalItem',
      2: 17,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 150,
      9: false,
      10: 'boolean',
      11: 'Is Local Item',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 3220,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Preserve Item',
      1: 'isPreserveList',
      2: 18,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 150,
      9: false,
      10: 'boolean',
      11: 'Preserve Item',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 3221,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    },
    {
      0: 'Must Stock',
      1: 'isMustStock',
      2: 19,
      3: true,
      4: false,
      5: false,
      6: false,
      7: 0,
      8: 150,
      9: false,
      10: 'boolean',
      11: 'Must Stock',
      12: '',
      13: '',
      14: '',
      15: '',
      16: 0,
      17: 3222,
      18: 0,
      FilterTemplate: '',
      Template: '',
      columnMenu: true
    }
  ],
  PogData: {
    calltype: 'model',
    planogramleft: {
      actAdds: 45,
      actDeletes: 0,
      actSwaps: 0,
      active: true,
      approveState: 'N',
      availableLinear: 99.2,
      bayProfile: null,
      cOptimized: true,
      cPogScore: '34.38',
      cPogWhiteSpace: null,
      cached: true,
      classification: 'Manual Set Size',
      clusterName: 'Nor Cal/Mainstream',
      corpId: 4,
      createdBy: 'Automation',
      createdIn: 1,
      createdTime: null,
      currentPog: 0,
      depth: 20,
      displayVersion: '1509918_3',
      droppedCount: 76,
      eTag: '',
      favorite: false,
      fixtures: 10,
      footage: '80x204x20',
      groupId: 374,
      groupName: null,
      height: 80,
      isOptimized: true,
      isReadOnly: true,
      l1: 'GM/HBC',
      l2: 'FAMILY CARE GMHBC',
      l3: 'BABY DIAPER',
      l4: 'Nor Cal/Mainstream',
      l5: '17-00',
      l6: 'A-DS-ST-80',
      l7: null,
      l8: null,
      l9: null,
      l10: null,
      lastUpdated: '2020-12-08T05:04:41.7570509Z',
      mPogName: '17\' BABY DIAPER PANTS X3',
      modelChangeReason: null,
      modelChanged: false,
      modelPogId: 1510020,
      modifiedBy: 'test@.com',
      modules: 1,
      noOfOffSets: 0,
      noOfProducts: 121,
      origModel: 1510020,
      p1: 37.19,
      p1_original: 'C-1.17-37.19',
      p2: 0,
      p2_original: 'N-0-0',
      p3: 0,
      p3_original: 'N-0-0',
      p4: 0,
      p4_original: 'N-0-0',
      p5: 0,
      p5_original: 'N-0-0',
      partitionKey: '912',
      pinned: false,
      pogAssignmentType: 0,
      pogName: '17\' BABY DIAPER PANTS X3',
      pogType: 'L',
      profile: null,
      qualifier: '017W_001M_010F',
      recAdds: 0,
      recDeletes: 0,
      recSwaps: 0,
      refStoreId: 0,
      requestId: null,
      retainCount: 0,
      rowKey: '1509918',
      ruleSetId: 0,
      score: 37,
      score_original: '37',
      spaceUtilized: 788.8,
      status: 5,
      statusCode: 'L',
      stockingSection: 'BABY DIAPER',
      stockingSectionId: '6515',
      storePercentage: 0,
      stores: 0,
      timestamp: '2020-12-02T04:59:57.5376968+00:00',
      totalLinear: 888,
      whiteSpace: 11.17,
      width: 204
    },
    planogramright: {
      actAdds: 45,
      actDeletes: 0,
      actSwaps: 0,
      active: true,
      approveState: 'N',
      availableLinear: 99.2,
      bayProfile: null,
      cOptimized: true,
      cPogScore: '34.38',
      cPogWhiteSpace: null,
      cached: true,
      classification: 'Manual Set Size',
      clusterName: 'Nor Cal/Mainstream',
      corpId: 4,
      createdBy: 'Automation',
      createdIn: 1,
      createdTime: null,
      currentPog: 0,
      depth: 20,
      displayVersion: '1509918_3',
      droppedCount: 76,
      eTag: '',
      favorite: false,
      fixtures: 10,
      footage: '80x204x20',
      groupId: 374,
      groupName: null,
      height: 80,
      isOptimized: true,
      isReadOnly: true,
      l1: 'GM/HBC',
      l2: 'FAMILY CARE GMHBC',
      l3: 'BABY DIAPER',
      l4: 'Nor Cal/Mainstream',
      l5: '17-00',
      l6: 'A-DS-ST-80',
      l7: null,
      l8: null,
      l9: null,
      l10: null,
      lastUpdated: '2020-12-08T05:04:41.7570509Z',
      mPogName: '17\' BABY DIAPER PANTS X3',
      modelChangeReason: null,
      modelChanged: false,
      modelPogId: 1510020,
      modifiedBy: 'test@.com',
      modules: 1,
      noOfOffSets: 0,
      noOfProducts: 121,
      origModel: 1510020,
      p1: 37.19,
      p1_original: 'C-1.17-37.19',
      p2: 0,
      p2_original: 'N-0-0',
      p3: 0,
      p3_original: 'N-0-0',
      p4: 0,
      p4_original: 'N-0-0',
      p5: 0,
      p5_original: 'N-0-0',
      partitionKey: '912',
      pinned: false,
      pogAssignmentType: 0,
      pogName: '17\' BABY DIAPER PANTS X3',
      pogType: 'L',
      profile: null,
      qualifier: '017W_001M_010F',
      recAdds: 0,
      recDeletes: 0,
      recSwaps: 0,
      refStoreId: 0,
      requestId: null,
      retainCount: 0,
      rowKey: '1509918',
      ruleSetId: 0,
      score: 37,
      score_original: '37',
      spaceUtilized: 788.8,
      status: 5,
      statusCode: 'L',
      stockingSection: 'BABY DIAPER',
      stockingSectionId: '6515',
      storePercentage: 0,
      stores: 0,
      timestamp: '2020-12-02T04:59:57.5376968+00:00',
      totalLinear: 888,
      whiteSpace: 11.17,
      width: 204
    },
    scenarioid: 912
  }
};
