export interface DeletePogTemplateResponseVM {
    iD: number;
    iDPOG: string;
    iDCorp: number;
    name: string;
    height: string;
    length: string;
    depth: string;
    nHeight: number;
    nLength: number;
    nDepth: number;
    measurement: string;
    fixtL1: string;
    fixtL2: string;
    fixtL3: string;
    fixtL4: string;
    fixtL5: string;
    fixtL6: string;
    fixtL7: string;
    fixtL8: string;
    fixtL9: string;
    fixtL10: string;
    pogType: number;
    image: string;
    fixtCreatedDate: string;
    fixtCreatedBy: string;
    fixtLastModifiedDate: string;
    fixtLastModifiedBy: string;
}