export const AppConstantSpace =
{
  MAX_FACINGX_MSG: ' You are exceeding Max Facings for Product ',
  MIN_FACINGX_MSG: ` You can't be lower then Min Facings for Product `,
  MAX_FACINGY_MSG: ' You are exceeding Max FacingsY for Product ',
  MIN_FACINGY_MSG: ` You can't be lower then Min FacingsY for Product `,
  MAX_LAYOVERS_MSG: ' You are exceeding Max LayoversY for Product ',
  MIN_LAYOVERS_MSG: ` You can't be lower then Min LayoversY for Product `,
  FACINGX: 'FacingsX',
  FACINGY: 'FacingsY',
  LAYOVERSY: 'LayoversY',
  ARD: 'ADRI',
  NUMERIC_RANGE: 'Numeric Range',
  STRING_MATCH: 'String Match',
  ASST_ACTION: 'Asst Action',
  CONVERT_TO_PIXEL_VALUE: 9.6,
  SPACE_NOT_AVAILABLE: ' No space available',
  CAN_NOT_ROTATE: ' Cannot Rotate ',
  SPACE_NOT_AVAILABLE_ROTATE: 'space not available with parent also for rotation',
  POSITIONOBJECT: 'Position',
  BLOCKOBJECT: 'Block',
  NESTEDBLOCKOBJECT: 'NestedBlock',
  BLOCKORDERPARENT: 'Parent',
  BLOCKORDERNESTED: 'Nested',
  FIXTUREOBJ: 'Fixture',
  GRILLOBJ: 'Grill',
  STANDARDSHELFOBJ: 'StandardShelf',
  PEGBOARDOBJ: 'Pegboard',
  SHOPPINGCARTOBJ: 'ShoppingCart',
  BLOCK_FIXTURE: 'BlockFixture',
  COFFINCASEOBJ: 'CoffinCase',
  SLOTWALLOBJ: 'Slotwall',
  CROSSBAROBJ: 'Crossbar',
  BASKETOBJ: 'Basket',
  SECTIONOBJ: 'Section',
  MODULAR: 'Modular',
  BAY: 'Bay',
  POG: 'POG',
  ANNOTATION: 'Annotation',
  DIVIDERS: 'Divider',
  BAGSHELF: 'BagShelf',
  MOVEMENT: 'LKFixtureMovement',
  SECTION: 'section',
  POSITION_LIKE: 'positionLike',
  OBJECT: 'object',
  FITCHECK_OK: 0,
  FITCHECK_COLLISION: 1,
  FITCHECK_TOO_TALL: 2,
  FITCHECK_OUTSIDE: 3,
  FITCHECK_TOO_TALL_OK: 4,
  FITCHECK_COLLISION_OK: 5,
  FITCHECK_OUTSIDE_OK: 6,
  FITCHECK_TOO_DEEP: 7,
  FITCHECK_TOO_DEEP_OK: 8,
  ON: 'ON',
  OFF: 'OFF',
  Collision: 'Collision',
  LOCATION_X: 'Location.X',
  LOCATION_Y: 'Location.Y',
  FIXTURE_WIDTH: 'Fixture.Width',
  STANDARDSHELF: 'standardshelf',
  PEGBOARD: 'pegboard',
  SLOTWALL: 'slotwall',
  CROSSBAR: 'crossbar',
  FIXTUREGALLERYPOGTYPE: -1,
  bayHighLighterZIndex: 10,
  spanShelfZIndex: 8,
  DIVIDEROBJECTMODEL: 7,
  FIXTUREOBJECTMODEL: 0,
  GRILLSOBJECTMODEL: 6,
  STANDARDSHELFOBJECTMODEL: 1,
  CROSSBAROBJECTMODEL: 2,
  PEGBOARDOBJECTMODEL: 3,
  BLOCKFIXTUREOBJECTMODEL: 5,
  POGSTATUS: {
    'EXPERIMENTAL': 1,
    'DRAFT': 2,
    'ACTIONABLE': 3,
    'PENDING': 4,
    'LIVE': 5,
    'RETIRED': 6
  },
  COFFINCASE: 'coffincase',
  BASKET: 'basket',
  SYSTEM: 'system',
  MERCH_DEFAULT: 100,
  MERCH_MULTI_ORIENT: 200,
  MERCH_PYRAMID_BASE: 300,
  MERCH_HALF_PYRAMID: 301,
  MERCH_PYRAMID: 302,
  MERCH_RECTANGLE_LOG: 303,
  MERCH_ABOVE: 305,
  MERCH_ABOVE_TEXT: '305',
  MERCH_BEHIND: 306,
  MERCH_BEHIND_TEXT: '306',
  MERCH_MANUAL: 307,
  MERCH_MANUAL_TEXT: '307',
  MERCH_BASKET: 400,
  MERCH_LOOSE: 500,
  MERCH_ADVANCED_TRAY: 101,
  FITCHECKTOLERANCE: 1,
  KEYDOWNEVENTJSON: {
    '<': 'FACINGSCHANGE',
    '>': 'FACINGSCHANGE',
    '49': 'FACINGSCHANGE',
    '50': 'FACINGSCHANGE',
    '51': 'FACINGSCHANGE',
    '52': 'FACINGSCHANGE',
    '53': 'FACINGSCHANGE',
    '54': 'FACINGSCHANGE',
    '55': 'FACINGSCHANGE',
    '56': 'FACINGSCHANGE ',
    '57': 'FACINGSCHANGE',
    '97': 'FACINGSCHANGE',
    '98': 'FACINGSCHANGE',
    '99': 'FACINGSCHANGE',
    '100': 'FACINGSCHANGE',
    '101': 'FACINGSCHANGE',
    '102': 'FACINGSCHANGE',
    '103': 'FACINGSCHANGE',
    '104': 'FACINGSCHANGE',
    '105': 'FACINGSCHANGE',
    '46': 'DELETE'
  },
  SHIFTKEYDOWNEVENTJSON: {
    '<': 'FACINGSCHANGE',
    '>': 'FACINGSCHANGE',
    '38': 'ROLLUPDOWN',
    '40': 'ROLLUPDOWN'
  },
  CTRLKEYDOWNEVENTJSON: {
    'v': 'PASTE',
    'c': 'COPY',
    'x': 'CUT',
    'i': 'FLIP',
    'ArrowLeft': 'MOVEPOS',
    'ArrowRight': 'MOVEPOS',
    'ArrowDown': 'MOVEFIX',
    'ArrowUp': 'MOVEFIX'
  },
  PROPERTYGRID_ALLOWED_DICTIONARIES: {
    'POSITION_PROPERTIES': [394],
    'FIXTURE_PROPERTIES': [],
    'SECTION_PROPERTIES': [219, 582]
  },
  DATE_TIME_FORMAT: 'dd MMM yyyy hh:mm:ss tt',
  DATE_FORMAT: 'dd MMM yyyy',
  ABSKEYGROUP: 'ABS',
  ACTIONS: {
    'FACINGS': 1,
    'DELETE': 2,
    'DRAGDROP': 3,
    'ORIENTATION': 4,
    'COPYPASTE': 5,
    'ALLOCATION': 6
  },
  CHILD_INTERSECTION_IDENTIFIER: 'Children-intersection',
  GERMAN_LANGUAGE_IDENTIFIER: 'de-DE',
  DEFAULT_PREVIEW_SMALL_IMAGE: '/Areas/ShelfPlanning/ClientApp/assets/images/default-preview-small.png',
  DEFAULT_PREVIEW_IMAGE: '/Areas/ShelfPlanning/ClientApp/assets/images/default-preview.gif',
  NO_IMAGE: '/Areas/iShelf/ClientApplication/appMaterial/css/themes/default/img/no-img.png',
  CLEAR_FOOTER_MSG_TIMER: 2500,
  PLANOGRAM_LIBRARY_PIN_STATUS: 'planogramLibraryPinStatus',
  SELECTALL:'selectAll',
  WHITESPACE:'whiteSpace',
  UP:'UP',
  DOWN:'DOWN',
  MULTIFIXEDIT: 'MULTIFIXEDIT',
  ADVANCEDTRAYCAPPING: {
    CAP_TRAY_FRONTS: 'advanced-unit-capping-fronts',
    CAP_TRAY_DEPTHS:'advanced-unit-capping-depths',
    CAP_TRAY_BOTH: 'advanced-unit-capping-both',
  }
}
